// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceAgent.Data;

#nullable disable

namespace ResourceAgent.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ResourceAgent.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Location = "Quartier Nord",
                            Quantity = 100,
                            Type = "Water"
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Location = "Quartier Nord",
                            Quantity = 50,
                            Type = "Food"
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            Location = "Quartier Sud",
                            Quantity = 30,
                            Type = "Blankets"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
